server:
  port: 8080

spring:
  application:
    name: Kino-CMS
  datasource:
    url: jdbc:postgresql://localhost:5432/kino-cms
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    username: test.in.odessa@gmail.com
    password:
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB